[package]
name = "html-tokenizer"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.8.2"
html5ever = "0.40.1"
serde_json = "1.0.151"
typed-arena = "2"

[[bench]]
name = "tokenize"
harness = false

# Comme release, mais avec les symboles de debug pour que le profileur
# puisse afficher les noms de fonctions.
[profile.profiling]
inherits = "release"
debug = true

[[bench]]
name = "parse"
harness = false
